# Generated by Django 4.1.7 on 2023-02-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
