# Generated by Django 4.1.7 on 2023-02-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_libro_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(max_length=500, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título del libro'),
        ),
    ]
