# Generated by Django 4.1.7 on 2023-02-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_libro_sinopsis_alter_libro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default=1, upload_to='images/libro/portadas/', verbose_name='Portada de libro'),
            preserve_default=False,
        ),
    ]
