# Generated by Django 4.1.7 on 2023-02-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
