# Generated by Django 4.1.7 on 2023-03-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_libro_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre del autor')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('pseudonimo', models.CharField(max_length=100, verbose_name='Pseudónimo')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fechaFallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de fallecimiento')),
                ('foto', models.ImageField(upload_to='images/autor/foto', verbose_name='Imagen del autor')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.autor', verbose_name='Elija al autor'),
        ),
    ]
