# Generated by Django 4.1.7 on 2023-03-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_autor_libro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(choices=[('mx', 'Mexicana'), ('usa', 'Estadounidense'), ('es', 'Española'), ('co', 'Colombia')], default='mx', max_length=100, verbose_name='Nacionalidad'),
        ),
    ]
