# Generated by Django 4.1.7 on 2023-03-13 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_autor_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Editorial')),
                ('telefono', models.CharField(max_length=15, null=True, unique=True, verbose_name='teléfono')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.editorial', verbose_name='Elija la editorial'),
        ),
    ]
